spring.application.name=bff
server.port=${BFF_PORT:8089}

urls.auth=http://${AUTH_SERVICE_HOST:localhost}:8081/api/auth
urls.products=http://${PRODUCTS_SERVICE_HOST:localhost}:8082/api/productos
urls.marketing=http://${MARKETING_SERVICE_HOST:localhost}:8083/api/marketing
urls.sales=http://${SALES_SERVICE_HOST:localhost}:8084/api/ordenes
urls.config=http://${CONFIG_SERVICE_HOST:localhost}:8085/api/config

resilience4j.circuitbreaker.instances.backendEcosistema.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.backendEcosistema.sliding-window-size=5
resilience4j.circuitbreaker.instances.backendEcosistema.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.backendEcosistema.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.backendEcosistema.permitted-number-of-calls-in-half-open-state=3